version: 2

############################################################################
references:
   default_environment_settings: &default_environment_settings
      docker:
        - image: zimbra/zcs-dev:8.8.9ga
      environment:
        - ANT_OPTS: -Dzimbra.buildinfo.version=8.7.6_GA
        - BUILD: "/home/build"
      working_directory: /home/build/zm-mailbox
   default_attach_workspace: &default_attach_workspace
         attach_workspace:
            at: /home/build
############################################################################

jobs:
  build:
    <<: *default_environment_settings
    steps:
      - add_ssh_keys:
          fingerprints: fa:6d:f0:c4:7d:0e:1f:aa:33:e7:83:fb:86:a2:cc:3d
      - checkout
      - run:
          name: Install ant-contrib
          command: sudo apt-get update; sudo apt-get install ant-contrib
      - run:
          name: Clone zm-timezones
          command: |
            cd "$BUILD"
            mkdir -p ~/.ivy2/cache
            mkdir -p /home/build/.zcs-deps
            mkdir -p /home/build/.ivy2/cache
            git clone -b develop https://github.com/Zimbra/zm-zcs.git 
            git clone -b develop https://github.com/Zimbra/zimbra-package-stub.git 
            sed -i 's,${dev.home},/home/build,g' /home/build/zm-zcs/ivysettings.xml
            sed -i 's,${dev.home},/home/build,g' /home/build/zm-mailbox/build-ivysettings.xml
            git clone https://github.com/Zimbra/zm-timezones.git -b develop --single-branch || exit 1
      - run:
          name: Clone zm-soap-harness
          command: |
            cd "$BUILD"
            git clone -b develop git@github.com:Zimbra/zm-soap-harness.git
      - run:
          name: Running ant compile in native directory
          command: ant clean compile publish-local
          working_directory: native
      - run:
          name: Running ant compile in common directory
          command: ant clean compile publish-local
          working_directory: common
      - run:
          name: Running ant compile in soap directory
          command: ant clean compile publish-local
          working_directory: soap
      - run:
          name: Running ant compile in client directory
          command: ant clean compile publish-local
          working_directory: client
      - run:
          name: Running ant compile in store directory
          command: ant clean compile publish-local
          working_directory: store
      - persist_to_workspace:
          root: /home/build/
          paths:
            - zm-timezones
            - zm-mailbox
            - zm-zcs
            - zimbra-package-stub
            - zm-soap-harness
            - .ssh
            - .zcs-deps
            - .ivy2/cache
  soap:
    <<: *default_environment_settings
    steps:
      - *default_attach_workspace
      - type: approval
      - run:
          name: Update Hostname
          command: |
            echo 34.93.135.71 zcs-dev.test instance-1.asia-south1-a.c.charming-well-247401.internal | sudo tee -a /etc/hosts
            cat /etc/hosts
            sed -i 's/zimbra.com/instance-1.asia-south1-a.c.charming-well-247401.internal/g' /home/build/zm-soap-harness/conf/global.properties
            sed -i 's/localhost/instance-1.asia-south1-a.c.charming-well-247401.internal/g' /home/build/zm-soap-harness/conf/global.properties
      - run:  
          name: Build soap harness jars
          command: | 
            cd /home/build/zm-soap-harness
            ant clean build-soap-data-file
      - run:
          name: Start soap tests execution
          command: |
            cd /home/build/zm-soap-harness
            sudo ant Run-SoapTestCore
  test:
    <<: *default_environment_settings
    steps:
      - *default_attach_workspace
      - run:
          name: Install npm
          command: sudo apt-get update -y; sudo apt-get -y install npm
      - run:
          name: Install nodejs
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install junit-merge
          command: sudo npm config set strict-ssl false && sudo npm install -g junit-merge
      - run:
          name: Create test report directory to hold junit tests
          command: mkdir -p /tmp/junit/
      - run:
          name: Running ant test native
          command: ant test
          working_directory: native
      - run:
          name: Running ant test common
          command: ant test
          working_directory: common
      - run:
          name: Running ant test soap
          command: ant test
          working_directory: soap
      - run:
          name: Running ant test client
          command: ant test
          working_directory: client
      - run:
          name: Running ant test store
          command: ant test
          no_output_timeout: 1200s
          working_directory: store
      - run:
          name: Finding test results
          command: find . -type f -regex ".*/build/test/report/.*xml" | xargs junit-merge
      - run:
          name: Copy test results to proper directory
          command: cp merged-test-results.xml /tmp/junit/
      - store_test_results:
          path: /tmp/junit/
############################################################################

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - soap:
          requires:
            - build
            - test
############################################################################
